[build]
  base = "apps/web"
  command = "pnpm install && pnpm --filter web build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200